# Generated by Django 4.2.30 on 2026-05-31 03:14

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("singleschema", "0002_rls"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("is_complete", models.BooleanField(default=False)),
                ("details", models.TextField(blank=True, default="")),
                (
                    "account",
                    models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="singleschema.account"),
                ),
            ],
            options={
                "base_manager_name": "all_tenants",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_tenants", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameModel(
            old_name="Project",
            new_name="Property",
        ),
        migrations.RenameModel(
            old_name="Task",
            new_name="Building",
        ),
        migrations.DeleteModel(
            name="Subtask",
        ),
        migrations.AddField(
            model_name="unit",
            name="building",
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="singleschema.building"),
        ),
    ]
