# Generated by Django 4.2.30 on 2026-05-31 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("singleschema", "0003_unit_rename_project_property_rename_task_building_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="building",
            old_name="project",
            new_name="property",
        ),
    ]
