# Generated by Django 4.2.30 on 2026-05-31 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("singleschema", "0004_rename_project_building_property"),
    ]

    operations = [
        migrations.RenameField(
            model_name="building",
            old_name="is_complete",
            new_name="has_units",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="is_complete",
        ),
    ]
